
### Spring properties
# Service registers under this name
spring:
  application:
    name: ZuulGateway

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
        
# HTTP Server (Tomcat) Port
server: 
  port: 8764
        
        
  #zuul 
  
zuul:
  routes:
    user:
      path: /u/**
      service-id: UserMicroservice
     # url: http://localhost:8081/user
    note:
      path: /n/**
      service-id: NoteMicroservice
    #  url: http://localhost:8082/note
    
    hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon: 
  ReadTimeout: 60000 
  ConnectTimeout: 60000 


  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
